import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { devProxyForMode } from "./src/config/devProxy.ts";

export default defineConfig(({ mode }) => ({
  plugins: [react()],
  server: {
    proxy: devProxyForMode(mode),
    watch: {
      ignored: ["**/coverage/**", "**/test-results/**", "**/playwright-report/**"],
    },
  },
  build: {
    target: "es2022",
    sourcemap: true,
    rolldownOptions: {
      output: {
        codeSplitting: {
          groups: [
            { name: "react-vendor", test: /node_modules[\\/](?:react|react-dom|react-redux|@reduxjs)/, priority: 30 },
            { name: "collaboration-vendor", test: /node_modules[\\/]@liveblocks/, priority: 25 },
            { name: "firebase-vendor", test: /node_modules[\\/](?:firebase|@firebase)/, priority: 20 },
            { name: "vendor", test: /node_modules/, minSize: 20_000, maxSize: 250_000, priority: 10 },
          ],
        },
      },
    },
  },
  test: {
    include: ["src/**/*.test.{ts,tsx}"],
    environment: "jsdom",
    globals: true,
    setupFiles: "./src/setupTests.ts",
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      include: ["src/**/*.{ts,tsx}", "api/**/*.ts"],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        "src/setupTests.ts",
        "src/vite-env.d.ts",
        "src/liveblocks.config.ts",
        "src/index.tsx",
        "src/e2e/**",
      ],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
        "src/editor/**": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/share-board.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/ShapeGraphic.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/EditorCanvas.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/PresentationView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/shapePaint.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/platform/recentBoards.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/useCollaborativeText.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/App.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "api/liveblocks-webhook.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/classes/shape.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/dashboard/activityCsv.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/layers.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/measurement.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/prototype.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/rulers.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/shapeAppearance.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/features/auth/authSlice.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_firebaseAdmin.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_http.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/session.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/router.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/mutations.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/brand/KumoLogo.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/dashboard/ActivityLog.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/OpenSessionView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/TextEditor.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/social/ProfileAvatar.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/config/firebase.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/features/editor/editorSlice.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/history/AutomaticVersionBridge.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/services/platformRepository.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_documentMutation.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_liveblocks.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_push.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/board-preview.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/ConnectionTelemetryBridge.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/OfflineRecoveryBridge.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/comments/useBoardCollaborators.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/dashboard/CommunityView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/history.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/services/fontRepository.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_platform.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_product.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_supabase.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/connectionTelemetry.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/comments/commentBody.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/graphics.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/shapeCreation.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/platform/observability.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/services/assetRepository.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/services/boardRepository.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/services/versionRepository.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_boardLinks.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_profiles.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_security.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/telemetry.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/offlineRecovery.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/config/localGoogleRedirect.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/connectorGeometry.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/history/VersionShareView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/platform/browserNotifications.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/services/productRepository.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/collaborators.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/comments/CommentsPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/dashboard/BoardCard.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/BoardNavigation.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/hierarchy.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_assets.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_boardSharing.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/services/apiClient.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/LiveblocksRoot.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/textCrdt.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/AdvancedShapeContent.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/PrototypeShareView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/snapping.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/workspace.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_boards.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_branchMerge.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/_boardThumbnail.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/friends.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/profile.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/liveblocks-auth.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/assets.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/boards.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/migrate-board.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/versions.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/branches.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/platform/productCapabilities.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/platform.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "server/api/handlers/product.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/handoff.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/designSystem.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/layout.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/advancedFeatures.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/export.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/commands.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/geometry.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/editor/useEditorActions.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/comments/CommentComposer.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/ExportPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/dashboard/SettingsView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/homepage/homePage.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/CommandPalette.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/PrototypePanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/InspectPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/dashboard/WorkspaceAdminView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/social/FriendsView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/social/ProfileView.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/collaboration/CollaborationBridge.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/comments/CommentPins.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/comments/CommentThread.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/BranchesPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/ProductPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/DesignLibraryPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/AdvancedStudioPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/EditorToolbar.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/history/VersionHistoryPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/dashboard/BoardDashboard.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/ShareDialog.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/LayersPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/InspectorPanel.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/editor/EditorWorkspace.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
        "src/components/homepage/MarketingCanvas.tsx": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
      },
    },
  },
}));
