import { Crown, Folder, UserPlus } from "@phosphor-icons/react";
import { useEffect, useMemo, useState } from "react";
import { ProfileAvatar } from "../social/ProfileAvatar";
import ui from "../ui/Ui.module.css";
import {
  cancelWorkspaceInvitation, inviteWorkspaceMember, loadWorkspaceAdmin, mutateWorkspaceFolder,
  removeWorkspaceMember, renameWorkspace, updateWorkspaceMember,
  transferWorkspaceOwnership,
  type WorkspaceAdminOverview, type WorkspaceRole,
} from "../../services/platformRepository";
import { createFolder } from "../../services/productRepository";
import styles from "./PlatformViews.module.css";

export const WorkspaceAdminView = () => {
  const [overview, setOverview] = useState<WorkspaceAdminOverview | null>(null);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<"admin" | "member" | "guest">("member");
  const [folderName, setFolderName] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [ownershipTarget, setOwnershipTarget] = useState<WorkspaceAdminOverview["members"][number] | null>(null);
  const [memberRemovalTarget, setMemberRemovalTarget] = useState<WorkspaceAdminOverview["members"][number] | null>(null);
  const [folderDeleteTarget, setFolderDeleteTarget] = useState<WorkspaceAdminOverview["folders"][number] | null>(null);
  const load = async () => { try { const result = await loadWorkspaceAdmin(); setOverview(result); setName(result.workspace.workspaces.name); setError(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Workspace could not be loaded."); } };
  useEffect(() => {
    let active = true;
    void loadWorkspaceAdmin().then((result) => {
      if (!active) return;
      setOverview(result);
      setName(result.workspace.workspaces.name);
      setError(null);
    }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "Workspace could not be loaded."); });
    return () => { active = false; };
  }, []);
  const children = useMemo(() => new Map((overview?.folders ?? []).map((folder) => [folder.id, overview!.folders.filter((candidate) => candidate.parent_id === folder.id)])), [overview]);
  if (!overview) return <section className={styles.view}><p role="status">Loading workspace administration…</p>{error && <p className={styles.error}>{error}</p>}</section>;
  const workspaceId = overview.workspace.workspace_id;
  const canAdmin = overview.workspace.role === "owner" || overview.workspace.role === "admin";
  return <section className={styles.view} aria-label="Workspace administration">
    <div className={styles.heading}><div><h1>Workspace</h1><p>Manage the people, roles, and nested folders that organize collaborative work.</p></div></div>
    <section className={styles.section}><h2>Workspace identity</h2><form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); void renameWorkspace(workspaceId, name).then(() => setMessage("Workspace renamed.")).catch((caught) => setError(caught instanceof Error ? caught.message : "Workspace could not be renamed.")); }}><input aria-label="Workspace name" value={name} onChange={(event) => setName(event.target.value)} disabled={!canAdmin} /><button className={`${ui.button} ${ui.buttonPrimary}`} type="submit" disabled={!canAdmin}>Save</button></form></section>
    <section className={styles.section}><h2>Members</h2>{canAdmin && <form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); void inviteWorkspaceMember(workspaceId, email, role).then((result) => { setEmail(""); setMessage(result.added ? "Member added." : result.delivery === "sent" ? "Invitation sent." : `Invitation created: ${result.url}`); return load(); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Workspace invitation could not be sent.")); }}><input aria-label="Workspace invite email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="teammate@example.com" required /><select aria-label="Workspace invite role" value={role} onChange={(event) => setRole(event.target.value as typeof role)}><option value="admin">Admin</option><option value="member">Member</option><option value="guest">Guest</option></select><button type="submit" className={`${ui.button} ${ui.buttonPrimary}`}><UserPlus aria-hidden="true" /> Invite</button></form>}
      <div className={styles.list}>{overview.members.map((member) => <div className={styles.row} key={member.user_id}><span className={styles.identity}><ProfileAvatar name={member.profile?.display_name ?? "Kumo user"} avatarUrl={member.profile?.avatar_url ?? null} size={32} /><span><strong>{member.profile?.display_name ?? "Kumo user"}</strong><small>{member.profile?.email ?? member.user_id}</small></span></span>{member.role === "owner" ? <small>Owner</small> : <select aria-label={`Workspace role for ${member.profile?.display_name ?? member.user_id}`} value={member.role} disabled={!canAdmin} onChange={(event) => void updateWorkspaceMember(workspaceId, member.user_id, event.target.value as Exclude<WorkspaceRole, "owner">).then(load)}><option value="admin">Admin</option><option value="member">Member</option><option value="guest">Guest</option></select>}{overview.workspace.role === "owner" && member.role !== "owner" && <button type="button" className={`${ui.button} ${ui.buttonGhost}`} onClick={() => setOwnershipTarget(member)}><Crown aria-hidden="true" /> Make owner</button>}{canAdmin && member.role !== "owner" && <button type="button" className={`${ui.button} ${ui.buttonGhost}`} onClick={() => setMemberRemovalTarget(member)}>Remove</button>}</div>)}</div>
      {overview.invitations.map((invitation) => <div className={styles.row} key={invitation.id}><span className={styles.identity}><span><strong>{invitation.email}</strong><small>Pending {invitation.role} · expires {new Date(invitation.expires_at).toLocaleDateString()}</small></span></span><button type="button" className={`${ui.button} ${ui.buttonGhost}`} onClick={() => void cancelWorkspaceInvitation(workspaceId, invitation.id).then(load)}>Cancel</button></div>)}
    </section>
    <section className={styles.section}><h2>Folders</h2><form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); void createFolder(folderName).then(() => { setFolderName(""); return load(); }); }}><input aria-label="Workspace folder name" value={folderName} onChange={(event) => setFolderName(event.target.value)} placeholder="New folder" /><button type="submit" className={`${ui.button} ${ui.buttonPrimary}`}><Folder aria-hidden="true" /> Create</button></form><div className={styles.list}>{overview.folders.map((folder) => <div className={`${styles.row} ${folder.parent_id ? styles.nested : ""}`} key={folder.id}><input aria-label={`Folder name for ${folder.name}`} defaultValue={folder.name} onBlur={(event) => { if (event.target.value !== folder.name) void mutateWorkspaceFolder("rename-folder", workspaceId, folder.id, { name: event.target.value }).then(load); }} /><select aria-label={`Parent folder for ${folder.name}`} value={folder.parent_id ?? ""} onChange={(event) => void mutateWorkspaceFolder("move-folder", workspaceId, folder.id, { parentId: event.target.value || null }).then(load).catch((caught) => setError(caught instanceof Error ? caught.message : "Folder could not be moved."))}><option value="">Top level</option>{overview.folders.filter((candidate) => candidate.id !== folder.id && !children.get(folder.id)?.some((child) => child.id === candidate.id)).map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select><button type="button" className={`${ui.button} ${ui.buttonGhost}`} onClick={() => setFolderDeleteTarget(folder)}>Delete</button></div>)}</div></section>
    {ownershipTarget && <div className={styles.dialogBackdrop} role="presentation"><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="transfer-workspace-title"><h2 id="transfer-workspace-title">Transfer workspace ownership?</h2><p>{ownershipTarget.profile?.display_name ?? ownershipTarget.profile?.email ?? "This member"} will become the owner. Your role will change to admin.</p><div className={styles.dialogActions}><button type="button" className={`${ui.button} ${ui.buttonGhost}`} onClick={() => setOwnershipTarget(null)}>Cancel</button><button type="button" className={`${ui.button} ${ui.buttonDanger}`} onClick={() => void transferWorkspaceOwnership(workspaceId, ownershipTarget.user_id).then(() => { setOwnershipTarget(null); setMessage("Workspace ownership transferred."); return load(); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Ownership could not be transferred."))}>Transfer ownership</button></div></section></div>}
    {memberRemovalTarget && <div className={styles.dialogBackdrop} role="presentation"><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="remove-member-title"><h2 id="remove-member-title">Remove workspace member?</h2><p>{memberRemovalTarget.profile?.display_name ?? memberRemovalTarget.profile?.email ?? "This member"} will immediately lose access to workspace boards and folders.</p><div className={styles.dialogActions}><button type="button" className={`${ui.button} ${ui.buttonGhost}`} onClick={() => setMemberRemovalTarget(null)}>Keep member</button><button type="button" className={`${ui.button} ${ui.buttonDanger}`} onClick={() => void removeWorkspaceMember(workspaceId, memberRemovalTarget.user_id).then(() => { setMemberRemovalTarget(null); setMessage("Workspace member removed."); return load(); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Member could not be removed."))}>Remove member</button></div></section></div>}
    {folderDeleteTarget && <div className={styles.dialogBackdrop} role="presentation"><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="delete-folder-title"><h2 id="delete-folder-title">Delete folder and nested folders?</h2><p>“{folderDeleteTarget.name}” and its nested folder structure will be removed. Boards remain in the workspace and can be reorganized.</p><div className={styles.dialogActions}><button type="button" className={`${ui.button} ${ui.buttonGhost}`} onClick={() => setFolderDeleteTarget(null)}>Keep folder</button><button type="button" className={`${ui.button} ${ui.buttonDanger}`} onClick={() => void mutateWorkspaceFolder("delete-folder", workspaceId, folderDeleteTarget.id, { recursive: true }).then(() => { setFolderDeleteTarget(null); setMessage("Folder deleted."); return load(); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Folder could not be deleted."))}>Delete folder</button></div></section></div>}
    {message && <p className={styles.message} role="status">{message}</p>}{error && <p className={styles.error} role="alert">{error}</p>}
  </section>;
};
