begin;

create table if not exists public.board_open_sessions (
  id uuid primary key default gen_random_uuid(),
  board_id text not null references public.boards(id) on delete cascade,
  token_hash text not null unique,
  password_hash text,
  role text not null default 'viewer' check (role in ('viewer', 'editor')),
  expires_at timestamptz not null,
  created_by text not null references public.profiles(firebase_uid) on delete cascade,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  last_used_at timestamptz,
  use_count integer not null default 0 check (use_count >= 0)
);

create index if not exists board_open_sessions_board_idx
  on public.board_open_sessions(board_id, created_at desc);
create index if not exists board_open_sessions_active_idx
  on public.board_open_sessions(token_hash)
  where revoked_at is null;

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.profiles(firebase_uid) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_success_at timestamptz,
  failure_count integer not null default 0 check (failure_count >= 0)
);

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions(user_id, updated_at desc);

create table if not exists public.workspace_fonts (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  family text not null,
  style text not null default 'normal',
  weight_min integer not null default 400 check (weight_min between 1 and 1000),
  weight_max integer not null default 400 check (weight_max between 1 and 1000),
  storage_key text not null unique,
  mime_type text not null check (mime_type in ('font/woff', 'font/woff2', 'font/ttf', 'font/otf')),
  uploaded_by text not null references public.profiles(firebase_uid) on delete cascade,
  created_at timestamptz not null default now(),
  unique (workspace_id, family, style, weight_min, weight_max)
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('workspace-fonts', 'workspace-fonts', false, 10485760, array['font/woff', 'font/woff2', 'font/ttf', 'font/otf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.performance_events (
  id bigint generated by default as identity primary key,
  board_id text references public.boards(id) on delete cascade,
  actor_id text references public.profiles(firebase_uid) on delete set null,
  release text,
  route text not null,
  metric text not null,
  value double precision not null,
  rating text check (rating in ('good', 'needs-improvement', 'poor')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists performance_events_board_idx
  on public.performance_events(board_id, created_at desc);
create index if not exists performance_events_metric_idx
  on public.performance_events(metric, created_at desc);

alter table public.board_open_sessions enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.workspace_fonts enable row level security;
alter table public.performance_events enable row level security;

revoke all on public.board_open_sessions from anon, authenticated;
revoke all on public.push_subscriptions from anon, authenticated;
revoke all on public.workspace_fonts from anon, authenticated;
revoke all on public.performance_events from anon, authenticated;

grant all on table public.board_open_sessions to service_role;
grant all on table public.push_subscriptions to service_role;
grant all on table public.workspace_fonts to service_role;
grant all on table public.performance_events to service_role;
grant usage, select on sequence public.performance_events_id_seq to service_role;

commit;
